### ISSUE TITLE
Nancy logo use violation

### ISSUE THREAD

**Issue by thecodejunkie** [codeyu/nancy-realworld-example-app#2]
Hi

What a nice demo application you have created! Unfortunately we did notice that you are using a custom version of our logo. While the source code of Nancy is freely distributed under MIT, our logo is under stricter regulations and defined in our usage guidelines that you can find here https://github.com/NancyFx/Nancy.Portfolio/blob/master/guidelines/guidelines.md Please read the documentation and take the appropriate step(s) to resolve this small issue

Thanks!

**Comment by codeyu** [comment]
Hi, Andreas 
I'm sorry  I used a custom version of Nancy's logo.
Now, I have updated logo using `Silhouette + type (vertical)` .
please @ me again if I still have the use of the logo issue.
Thank you.

![](https://github.com/codeyu/nancy-realworld-example-app/blob/master/logo.png?raw=true)

**Comment by thecodejunkie** [comment]
👍 😄
